import { Plant } from '../types/plant'

export type PlantTemplate = Omit<
  Plant,
  'id' | 'photos' | 'lastWatered' | 'lastFertilized' | 'createdAt' | 'updatedAt'
> & {
  /** Weitere gebräuchliche Namen/Synonyme für die Suche (z. B. "Friedenslilie" für das Einblatt). */
  aliases?: string[]
}

export const PLANT_TEMPLATES: PlantTemplate[] = [
  {
    name: 'Monstera',
    scientificName: 'Monstera deliciosa',
    aliases: ['Fensterblatt', 'Köstliches Fensterblatt'],
    description: 'Das Fensterblatt mit charakteristischen gelochten Blättern. Pflegeleicht und wächst schnell.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Erde leicht antrocknen lassen zwischen den Gaben. Im Winter seltener gießen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'April bis September alle zwei Wochen mit Grünpflanzendünger.',
      locationTips: 'Helles bis halbschattiges Licht ohne direkte Mittagssonne.',
      temperature: { min: 16, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Efeutute',
    scientificName: 'Epipremnum aureum',
    aliases: ['Pothos', 'Goldene Efeutute', 'Skindapsus'],
    description: 'Extrem robuste Hängepflanze. Verträgt wenig Licht und unregelmäßiges Gießen.',
    location: 'shade',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Erst gießen wenn die obere Erdschicht (2–3 cm) trocken ist.',
      fertilizingFrequencyDays: 21,
      fertilizingTips: 'In der Wachstumsphase alle drei Wochen dünn düngen.',
      locationTips: 'Sehr anpassungsfähig – von hell bis halbschattig.',
      temperature: { min: 15, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Gummibaum',
    scientificName: 'Ficus elastica',
    aliases: ['Birkenfeige', 'Ficus'],
    description: 'Klassischer Zimmerbaum mit glänzend dunkelgrünen Blättern.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Mäßig gießen, zwischen den Gaben gut abtrocknen lassen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'März bis September alle zwei Wochen flüssig düngen.',
      locationTips: 'Heller Standort, verträgt Morgensonne. Kein Zugluft.',
      temperature: { min: 15, max: 30 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Aloe Vera',
    scientificName: 'Aloe vera',
    aliases: ['Echte Aloe', 'Wüstenlilie'],
    description: 'Sukkulente mit heilenden Eigenschaften. Braucht viel Sonne und wenig Wasser.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Erde komplett abtrocknen lassen. Staunässe unbedingt vermeiden.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Nur im Sommer 1× monatlich mit Kaktusdünger.',
      locationTips: 'Volle Sonne, südliches Fensterbrett ideal.',
      temperature: { min: 15, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Zamioculcas',
    scientificName: 'Zamioculcas zamiifolia',
    aliases: ['Glücksfeder', 'ZZ-Pflanze', 'Kartonpapierpflanze'],
    description: 'Glücksfeder – extrem genügsam, verträgt Trockenheit und wenig Licht.',
    location: 'shade',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Sehr selten gießen – lieber zu wenig als zu viel. Staunässe tötet die Pflanze.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Nur Frühling/Sommer 1× monatlich düngen.',
      locationTips: 'Kommt mit wenig Licht aus, mag aber hellen Standort ohne direkte Sonne.',
      temperature: { min: 16, max: 26 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Bogenhanf',
    scientificName: 'Sansevieria trifasciata',
    aliases: ['Sansevieria', 'Schwiegermutterzunge', 'Schlangenpflanze'],
    description: 'Schwertförmige Blätter, nahezu unzerstörbar. Ideal für Anfänger.',
    location: 'indoor',
    careInfo: {
      wateringFrequencyDays: 21,
      wateringTips: 'Sehr selten gießen – alle 3 Wochen reichen im Sommer, im Winter noch seltener.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'April bis August 1× monatlich mit Universaldünger (halbe Dosis).',
      locationTips: 'Toleriert alles von Vollschatten bis Vollsonne. Innenraum geeignet.',
      temperature: { min: 15, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Orchidee',
    scientificName: 'Phalaenopsis',
    aliases: ['Phalaenopsis', 'Schmetterlingsorchidee', 'Falterorchidee'],
    description: 'Elegante Blütenpracht. Braucht hellen Standort ohne direkte Sonne und hohe Luftfeuchtigkeit.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Einmal pro Woche kurz wässern oder Tauchbad (10 Min.). Wurzeln müssen abtrocknen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Wöchentlich mit Orchideendünger in halber Dosierung.',
      locationTips: 'Helles indirektes Licht, kein Zugluft, keine Heizungsluft.',
      temperature: { min: 18, max: 25 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Basilikum',
    scientificName: 'Ocimum basilicum',
    description: 'Aromatisches Küchenkraut. Braucht viel Sonne und regelmäßiges Gießen.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 3,
      wateringTips: 'Täglich kontrollieren – Basilikum mag gleichmäßig feuchte Erde. Nicht von oben gießen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Alle zwei Wochen mit Kräuterdünger.',
      locationTips: 'Vollsonniger Standort, südliches Fensterbrett oder draußen ab 15°C.',
      temperature: { min: 18, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Drachenbaum',
    scientificName: 'Dracaena marginata',
    aliases: ['Dracaena', 'Madagaskar-Drachenbaum'],
    description: 'Schlanker Baum mit schmalen Blättern, luftreinigend. Robust und pflegeleicht.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Erde oben leicht antrocknen lassen. Kein Kalkwasser – besser gefiltertes Wasser.',
      fertilizingFrequencyDays: 21,
      fertilizingTips: 'Frühling und Sommer alle 3 Wochen mit Grünpflanzendünger.',
      locationTips: 'Halbschattiger bis heller Standort. Kein direkte Mittagssonne.',
      temperature: { min: 15, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Kaktus',
    scientificName: 'Cactaceae',
    description: 'Pflegeleichteste Zimmerpflanze überhaupt. Braucht Sonne und sehr wenig Wasser.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 21,
      wateringTips: 'Im Sommer alle 2–3 Wochen. Im Winter kaum – Erde komplett trocken lassen.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Nur im Sommer 1× monatlich mit speziellem Kaktusdünger.',
      locationTips: 'Vollste Sonne, südliches Fensterbrett. Im Winter kühler Standort fördert Blüte.',
      temperature: { min: 10, max: 35 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Sukkulente',
    scientificName: 'Echeveria',
    aliases: ['Echeverie', 'Dickblatt'],
    description: 'Rosettenförmige Sukkulente mit fleischigen Blättern. Ideal für sonnige Fensterbänke.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Wenig gießen, Substrat vollständig abtrocknen lassen. Im Winter kaum Wasser.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'April bis Oktober 1× monatlich Kaktusdünger.',
      locationTips: 'Volles Sonnenlicht. Im Sommer auch draußen möglich.',
      temperature: { min: 10, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Friedenslilie',
    scientificName: 'Spathiphyllum',
    aliases: ['Einblatt', 'Blattfahne', 'Scheidenblatt'],
    description: 'Elegante Schattenpflanze mit weißen Blüten. Zeigt durch hängende Blätter Durst an.',
    location: 'shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Regelmäßig gießen, Erde leicht feucht halten. Hängende Blätter = sofort gießen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'März bis Oktober alle zwei Wochen mit Grünpflanzendünger.',
      locationTips: 'Halbschatten bis Schatten. Kein direktes Sonnenlicht.',
      temperature: { min: 16, max: 26 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Yucca-Palme',
    scientificName: 'Yucca elephantipes',
    aliases: ['Yucca', 'Palmlilie', 'Riesen-Palmlilie'],
    description: 'Markante Zimmerpflanze mit schwertförmigen Blättern auf einem dicken Stamm.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Erde gut abtrocknen lassen. Staunässe vermeiden. Im Winter sehr selten gießen.',
      fertilizingFrequencyDays: 21,
      fertilizingTips: 'April bis August alle drei Wochen mit Flüssigdünger.',
      locationTips: 'Heller, sonniger Standort. Verträgt auch direkte Sonne.',
      temperature: { min: 10, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Grünlilie',
    scientificName: 'Chlorophytum comosum',
    aliases: ['Chlorophytum', 'Graslilie', 'Spinnenpflanze'],
    description: 'Unverwüstliche Hängepflanze mit grün-weiß gestreiften Blättern. Ideal für Anfänger.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Gleichmäßig feucht halten. Verträgt kurze Trockenperioden.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Frühling bis Herbst alle zwei Wochen düngen.',
      locationTips: 'Halbschatten bis helles indirektes Licht. Keine direkte Sonne.',
      temperature: { min: 12, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Zimmerlinde',
    scientificName: 'Sparrmannia africana',
    description: 'Großblättrige Zimmerpflanze mit weißen Blüten. Wächst schnell und braucht viel Platz.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 5,
      wateringTips: 'Regelmäßig und reichlich gießen. Erde nie komplett austrocknen lassen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Wachstumsphase alle zwei Wochen mit Flüssigdünger.',
      locationTips: 'Heller Standort ohne direkte Mittagssonne. Im Sommer auch draußen.',
      temperature: { min: 12, max: 24 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Philodendron',
    scientificName: 'Philodendron hederaceum',
    description: 'Robuste Kletterpflanze mit herzförmigen Blättern. Wächst schnell und ist sehr anpassungsfähig.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Obere Erdschicht antrocknen lassen, dann gründlich gießen. Im Winter weniger.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Frühling bis Herbst alle zwei Wochen mit Grünpflanzendünger.',
      locationTips: 'Helles bis halbschattiges Licht. Verträgt auch weniger Licht.',
      temperature: { min: 16, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Calathea',
    scientificName: 'Calathea orbifolia',
    aliases: ['Korbmarante', 'Pfauenpflanze', 'Schattenblume'],
    description: 'Kunstvoll gemusterte Blätter. Anspruchsvoll, aber ein echter Blickfang.',
    location: 'shade',
    careInfo: {
      wateringFrequencyDays: 5,
      wateringTips: 'Gleichmäßig feucht halten, nie nass. Nur weiches oder gefiltertes Wasser.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Frühling bis Herbst alle zwei Wochen mit verdünntem Grünpflanzendünger.',
      locationTips: 'Kein direktes Sonnenlicht. Feuchter, schattiger Standort ideal.',
      temperature: { min: 18, max: 26 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Geldbaum',
    scientificName: 'Crassula ovata',
    aliases: ['Pfennigbaum', 'Glücksbaum', 'Dickblatt', 'Crassula'],
    description: 'Sukkulente mit dicken, glänzenden Blättern. Gilt als Glücksbringer und wird sehr alt.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Sparsam gießen, Erde vollständig abtrocknen lassen. Im Winter fast kein Wasser.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Einmal monatlich von April bis September mit Sukkulentendünger.',
      locationTips: 'Heller, sonniger Standort. Verträgt direkte Sonne gut.',
      temperature: { min: 10, max: 28 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Schwertfarn',
    scientificName: 'Nephrolepis exaltata',
    aliases: ['Nephrolepis', 'Zimmerfarn', 'Boston-Farn'],
    description: 'Klassische Hängepflanze mit langen, herabhängenden Wedeln. Liebt hohe Luftfeuchtigkeit.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 4,
      wateringTips: 'Erde immer leicht feucht halten – Farne mögen keine Trockenheit. Regelmäßig besprühen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Alle zwei Wochen von April bis September mit verdünntem Flüssigdünger.',
      locationTips: 'Halbschattig, hohe Luftfeuchtigkeit. Ideal für Badezimmer.',
      temperature: { min: 15, max: 24 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Dieffenbachie',
    scientificName: 'Dieffenbachia seguine',
    description: 'Große, grün-weiß gemusterte Blätter. Achtung: Der Pflanzensaft ist giftig.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Gleichmäßig feucht halten, keine Staunässe. Im Winter weniger gießen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Alle zwei Wochen von März bis Oktober mit Grünpflanzendünger.',
      locationTips: 'Helles, indirektes Licht. Keine direkte Sonne.',
      temperature: { min: 18, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Flamingoblume',
    scientificName: 'Anthurium andreanum',
    aliases: ['Anthurie', 'Anthurium', 'Flamingblume'],
    description: 'Lackartig glänzende rote oder pinke Hochblätter. Blüht bei guter Pflege fast ganzjährig.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Erde gleichmäßig feucht halten, nie austrocknen lassen. Regelmäßig besprühen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Alle zwei Wochen mit Blühpflanzendünger von März bis Oktober.',
      locationTips: 'Helles, indirektes Licht ohne direkte Sonne. Keine Zugluft.',
      temperature: { min: 18, max: 28 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Strelitzie',
    scientificName: 'Strelitzia reginae',
    aliases: ['Paradiesvogelblume', 'Papageienblume'],
    description: 'Tropisches Highlight mit Blüten wie Paradiesvögel. Braucht viel Licht und Platz.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Mäßig gießen, Erde zwischen den Gaben leicht abtrocknen lassen. Im Winter weniger.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Von März bis September alle zwei Wochen mit Blühpflanzendünger.',
      locationTips: 'Sehr heller, sonniger Standort. Sommer gerne draußen.',
      temperature: { min: 12, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Elefantenohr',
    scientificName: 'Alocasia macrorrhiza',
    aliases: ['Alocasia', 'Pfeilblatt', 'Riesenblatt'],
    description: 'Riesige, herzförmige Blätter. Tropische Schönheit für helle, feuchte Räume.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 5,
      wateringTips: 'Erde gleichmäßig feucht halten, nicht austrocknen lassen, keine Staunässe.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Alle zwei Wochen von März bis September mit Grünpflanzendünger.',
      locationTips: 'Helles, indirektes Licht. Keine direkte Sonne.',
      temperature: { min: 18, max: 28 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Bromelie',
    scientificName: 'Guzmania lingulata',
    description: 'Leuchtend farbige Hochblätter. Tropisch, pflegeleicht und langlebig.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Wasser in die Blatttrichter füllen und alle 2 Wochen wechseln. Erde nur leicht feucht.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Einmal monatlich verdünnten Flüssigdünger in die Trichter geben.',
      locationTips: 'Helles, indirektes Licht. Keine direkte Mittagssonne.',
      temperature: { min: 18, max: 28 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Perlenschnur',
    scientificName: 'Senecio rowleyanus',
    aliases: ['Erbsenpflanze', 'Senecio', 'Perlenkette'],
    description: 'Außergewöhnliche Sukkulente mit kugeligen Blättern an langen Trieben. Toll als Hängepflanze.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Sehr selten gießen – nur wenn Perlen schrumpelig werden. Erde vollständig abtrocknen lassen.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Einmal monatlich im Sommer mit stark verdünntem Sukkulentendünger.',
      locationTips: 'Helles bis sonniges Fensterbrett, verträgt Direktsonne.',
      temperature: { min: 10, max: 28 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Rosmarin',
    scientificName: 'Salvia rosmarinus',
    description: 'Aromatisches Küchenkraut mit nadelartigen Blättern. Braucht viel Sonne, verträgt Trockenheit.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Mäßig gießen, Erde leicht antrocknen lassen. Staunässe ist tödlich.',
      fertilizingFrequencyDays: 21,
      fertilizingTips: 'Alle drei Wochen von März bis September mit Kräuterdünger.',
      locationTips: 'Vollsonniger Standort. Liebt Südbalkon oder Küchenfenster.',
      temperature: { min: 5, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Pfefferminze',
    scientificName: 'Mentha × piperita',
    aliases: ['Minze', 'Mentha'],
    description: 'Vielseitiges Küchenkraut für Tee und Kochen. Wächst schnell, braucht regelmäßiges Ernten.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 3,
      wateringTips: 'Gleichmäßig feucht halten, keine Staunässe. Lieber öfter wenig als selten viel.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Alle zwei Wochen mit Kräuterdünger in halber Dosierung.',
      locationTips: 'Halbschattiger Standort, verträgt auch etwas Sonne.',
      temperature: { min: 8, max: 25 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Lavendel',
    scientificName: 'Lavandula angustifolia',
    description: 'Duftet herrlich und beruhigt. Als Topfpflanze auf Balkon oder Fensterbank ein Mittelmeer-Flair.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Mäßig gießen, gut abtrocknen lassen. Staunässe ist die häufigste Todesursache.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Einmal monatlich im Frühling/Sommer oder gar nicht – Lavendel mag magere Böden.',
      locationTips: 'Vollsonniger Standort, mindestens 6 Stunden Sonne täglich.',
      temperature: { min: -10, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Thymian',
    scientificName: 'Thymus vulgaris',
    description: 'Anspruchsloses, aromatisches Küchenkraut. Braucht viel Sonne und wenig Wasser.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Mäßig gießen, Erde gut abtrocknen lassen. Lieber zu trocken als zu nass.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Sparsam düngen – zu viel Dünger mindert das Aroma.',
      locationTips: 'Sonnigster Platz im Haus oder auf dem Balkon.',
      temperature: { min: 5, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Chilipflanze',
    scientificName: 'Capsicum annuum',
    description: 'Dekorativ und praktisch auf der Fensterbank. Mit den richtigen Sorten ganzjährig Ernte.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 4,
      wateringTips: 'Gleichmäßig feucht halten, keine Staunässe. Im Sommer regelmäßiger gießen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Alle zwei Wochen mit Tomatendünger ab der Blüte.',
      locationTips: 'Vollsonniger Standort, mindestens 6 Stunden Sonne. Südbalkon ideal.',
      temperature: { min: 15, max: 32 },
      humidity: 'medium',
    },
    diseases: [],
  },
]
