import { Plant } from '../types/plant'

export type PlantTemplate = Omit<Plant, 'id' | 'photos' | 'lastWatered' | 'lastFertilized' | 'createdAt' | 'updatedAt'>

export const PLANT_TEMPLATES: PlantTemplate[] = [
  {
    name: 'Monstera',
    scientificName: 'Monstera deliciosa',
    description: 'Das Fensterblatt mit charakteristischen gelochten Blättern. Pflegeleicht und wächst schnell.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Erde leicht antrocknen lassen zwischen den Gaben. Im Winter seltener gießen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'April bis September alle zwei Wochen mit Grünpflanzendünger.',
      locationTips: 'Helles bis halbschattiges Licht ohne direkte Mittagssonne.',
      temperature: { min: 16, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Efeutute',
    scientificName: 'Epipremnum aureum',
    description: 'Extrem robuste Hängepflanze. Verträgt wenig Licht und unregelmäßiges Gießen.',
    location: 'shade',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Erst gießen wenn die obere Erdschicht (2–3 cm) trocken ist.',
      fertilizingFrequencyDays: 21,
      fertilizingTips: 'In der Wachstumsphase alle drei Wochen dünn düngen.',
      locationTips: 'Sehr anpassungsfähig – von hell bis halbschattig.',
      temperature: { min: 15, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Gummibaum',
    scientificName: 'Ficus elastica',
    description: 'Klassischer Zimmerbaum mit glänzend dunkelgrünen Blättern.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Mäßig gießen, zwischen den Gaben gut abtrocknen lassen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'März bis September alle zwei Wochen flüssig düngen.',
      locationTips: 'Heller Standort, verträgt Morgensonne. Kein Zugluft.',
      temperature: { min: 15, max: 30 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Aloe Vera',
    scientificName: 'Aloe vera',
    description: 'Sukkulente mit heilenden Eigenschaften. Braucht viel Sonne und wenig Wasser.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Erde komplett abtrocknen lassen. Staunässe unbedingt vermeiden.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Nur im Sommer 1× monatlich mit Kaktusdünger.',
      locationTips: 'Volle Sonne, südliches Fensterbrett ideal.',
      temperature: { min: 15, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Zamioculcas',
    scientificName: 'Zamioculcas zamiifolia',
    description: 'Glücksfeder – extrem genügsam, verträgt Trockenheit und wenig Licht.',
    location: 'shade',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Sehr selten gießen – lieber zu wenig als zu viel. Staunässe tötet die Pflanze.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Nur Frühling/Sommer 1× monatlich düngen.',
      locationTips: 'Kommt mit wenig Licht aus, mag aber hellen Standort ohne direkte Sonne.',
      temperature: { min: 16, max: 26 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Bogenhanf',
    scientificName: 'Sansevieria trifasciata',
    description: 'Schwertförmige Blätter, nahezu unzerstörbar. Ideal für Anfänger.',
    location: 'indoor',
    careInfo: {
      wateringFrequencyDays: 21,
      wateringTips: 'Sehr selten gießen – alle 3 Wochen reichen im Sommer, im Winter noch seltener.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'April bis August 1× monatlich mit Universaldünger (halbe Dosis).',
      locationTips: 'Toleriert alles von Vollschatten bis Vollsonne. Innenraum geeignet.',
      temperature: { min: 15, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Orchidee',
    scientificName: 'Phalaenopsis',
    description: 'Elegante Blütenpracht. Braucht hellen Standort ohne direkte Sonne und hohe Luftfeuchtigkeit.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Einmal pro Woche kurz wässern oder Tauchbad (10 Min.). Wurzeln müssen abtrocknen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Wöchentlich mit Orchideendünger in halber Dosierung.',
      locationTips: 'Helles indirektes Licht, kein Zugluft, keine Heizungsluft.',
      temperature: { min: 18, max: 25 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Basilikum',
    scientificName: 'Ocimum basilicum',
    description: 'Aromatisches Küchenkraut. Braucht viel Sonne und regelmäßiges Gießen.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 3,
      wateringTips: 'Täglich kontrollieren – Basilikum mag gleichmäßig feuchte Erde. Nicht von oben gießen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Alle zwei Wochen mit Kräuterdünger.',
      locationTips: 'Vollsonniger Standort, südliches Fensterbrett oder draußen ab 15°C.',
      temperature: { min: 18, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Drachenbaum',
    scientificName: 'Dracaena marginata',
    description: 'Schlanker Baum mit schmalen Blättern, luftreinigend. Robust und pflegeleicht.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 10,
      wateringTips: 'Erde oben leicht antrocknen lassen. Kein Kalkwasser – besser gefiltertes Wasser.',
      fertilizingFrequencyDays: 21,
      fertilizingTips: 'Frühling und Sommer alle 3 Wochen mit Grünpflanzendünger.',
      locationTips: 'Halbschattiger bis heller Standort. Kein direkte Mittagssonne.',
      temperature: { min: 15, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Kaktus',
    scientificName: 'Cactaceae',
    description: 'Pflegeleichteste Zimmerpflanze überhaupt. Braucht Sonne und sehr wenig Wasser.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 21,
      wateringTips: 'Im Sommer alle 2–3 Wochen. Im Winter kaum – Erde komplett trocken lassen.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'Nur im Sommer 1× monatlich mit speziellem Kaktusdünger.',
      locationTips: 'Vollste Sonne, südliches Fensterbrett. Im Winter kühler Standort fördert Blüte.',
      temperature: { min: 10, max: 35 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Sukkulente',
    scientificName: 'Echeveria',
    description: 'Rosettenförmige Sukkulente mit fleischigen Blättern. Ideal für sonnige Fensterbänke.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Wenig gießen, Substrat vollständig abtrocknen lassen. Im Winter kaum Wasser.',
      fertilizingFrequencyDays: 30,
      fertilizingTips: 'April bis Oktober 1× monatlich Kaktusdünger.',
      locationTips: 'Volles Sonnenlicht. Im Sommer auch draußen möglich.',
      temperature: { min: 10, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Friedenslilie',
    scientificName: 'Spathiphyllum',
    description: 'Elegante Schattenpflanze mit weißen Blüten. Zeigt durch hängende Blätter Durst an.',
    location: 'shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Regelmäßig gießen, Erde leicht feucht halten. Hängende Blätter = sofort gießen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'März bis Oktober alle zwei Wochen mit Grünpflanzendünger.',
      locationTips: 'Halbschatten bis Schatten. Kein direktes Sonnenlicht.',
      temperature: { min: 16, max: 26 },
      humidity: 'high',
    },
    diseases: [],
  },
  {
    name: 'Yucca-Palme',
    scientificName: 'Yucca elephantipes',
    description: 'Markante Zimmerpflanze mit schwertförmigen Blättern auf einem dicken Stamm.',
    location: 'sun',
    careInfo: {
      wateringFrequencyDays: 14,
      wateringTips: 'Erde gut abtrocknen lassen. Staunässe vermeiden. Im Winter sehr selten gießen.',
      fertilizingFrequencyDays: 21,
      fertilizingTips: 'April bis August alle drei Wochen mit Flüssigdünger.',
      locationTips: 'Heller, sonniger Standort. Verträgt auch direkte Sonne.',
      temperature: { min: 10, max: 30 },
      humidity: 'low',
    },
    diseases: [],
  },
  {
    name: 'Grünlilie',
    scientificName: 'Chlorophytum comosum',
    description: 'Unverwüstliche Hängepflanze mit grün-weiß gestreiften Blättern. Ideal für Anfänger.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 7,
      wateringTips: 'Gleichmäßig feucht halten. Verträgt kurze Trockenperioden.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Frühling bis Herbst alle zwei Wochen düngen.',
      locationTips: 'Halbschatten bis helles indirektes Licht. Keine direkte Sonne.',
      temperature: { min: 12, max: 28 },
      humidity: 'medium',
    },
    diseases: [],
  },
  {
    name: 'Zimmerlinde',
    scientificName: 'Sparrmannia africana',
    description: 'Großblättrige Zimmerpflanze mit weißen Blüten. Wächst schnell und braucht viel Platz.',
    location: 'partial-shade',
    careInfo: {
      wateringFrequencyDays: 5,
      wateringTips: 'Regelmäßig und reichlich gießen. Erde nie komplett austrocknen lassen.',
      fertilizingFrequencyDays: 14,
      fertilizingTips: 'Wachstumsphase alle zwei Wochen mit Flüssigdünger.',
      locationTips: 'Heller Standort ohne direkte Mittagssonne. Im Sommer auch draußen.',
      temperature: { min: 12, max: 24 },
      humidity: 'medium',
    },
    diseases: [],
  },
]
